# Getting all arrivals to all stops of a given line in a given day

## Install dependencies

This notebook requires two dependencies which can be installed with the following command `pip install pandas open-bus-stride-client`.

You can also launch it online at [this URL](https://mybinder.org/v2/gh/hasadna/open-bus-stride-client/HEAD?labpath=notebooks%2Fgetting%20all%20arrivals%20to%20all%20stops%20of%20a%20given%20line%20in%20a%20given%20day.ipynb), when launching online the dependencies are already installed.

## Import dependencies

In [1]:
import datetime

from ipywidgets import DatePicker
from IPython.display import display

# we use pandas to visualize the results we get
import pandas as pd

# The stride client library, used to make the calls to the stride api
import stride

# For local development, set the following to connect to local api:
# stride.config.STRIDE_API_BASE_URL = "http://localhost:8000"

## Pick a date

First, we pick the day we want to analyze, GTFS data queries should be limited to a specific date

You can use the date picker to choose a date which will be used in the next code blocks

In [2]:
date_widget = DatePicker(description='Date:', value=datetime.date(2022,6,2))
display(date_widget)

DatePicker(value=datetime.date(2022, 6, 2), description='Date:')

## Get list of GTFS Routes

For this example we get routes based on route_short_name which is usually the route number in the GTFS data

We look for all routes on the given day matchin route_short_name `360`

In [3]:
gtfs_routes = stride.get('/gtfs_routes/list', {
    'date_from': date_widget.value, 'date_to': date_widget.value,
    'route_short_name': 360,
}, pre_requests_callback='print')
pd.DataFrame(gtfs_routes)

https://open-bus-stride-api.hasadna.org.il/gtfs_routes/list?date_from=2022-06-02&date_to=2022-06-02&route_short_name=360

,id,date,line_ref,operator_ref,route_short_name,route_long_name,route_mkt,route_direction,route_alternative,agency_name,route_type
0,617862,2022-06-02,28774,4,360,היכל המשפט/אבא אבן-ירושלים<->סובת התאנה-אפרת-1#,14360,1,#,אגד תעבורה,3
1,617863,2022-06-02,28775,4,360,סובת התאנה-אפרת<->בנייני האומה/שדרות שז''ר-ירו...,14360,2,#,אגד תעבורה,3
2,618031,2022-06-02,29729,4,360,סובת התאנה-אפרת<->בנייני האומה/שדרות שז''ר-ירו...,14360,2,4,אגד תעבורה,3

## Get list of SIRI rides

Based on this list the GTFS line_refs and operator_refs we can get the list of SIRI rides which occured on these routes

We use the scheduled_start_time field which is populated from the SIRI data to limit the rides to the specific date we want to check

This data contains the duration_minutes field which is the duration of the ride from the SIRI data

In [4]:
siri_rides = stride.get('/siri_rides/list', {
    'scheduled_start_time_from': datetime.datetime.combine(date_widget.value, datetime.time(), datetime.timezone.utc),
    'scheduled_start_time_to': datetime.datetime.combine(date_widget.value, datetime.time(23,59), datetime.timezone.utc),
    'siri_route__line_refs': ','.join([str(gtfs_route['line_ref']) for gtfs_route in gtfs_routes]),
    'siri_route__operator_refs': ','.join([str(gtfs_route['operator_ref']) for gtfs_route in gtfs_routes]),
    'order_by': 'scheduled_start_time asc'
}, pre_requests_callback='print')
pd.DataFrame(siri_rides)

https://open-bus-stride-api.hasadna.org.il/siri_rides/list?scheduled_start_time_from=2022-06-02T00%3A00%3A00.000000%2B0000&scheduled_start_time_to=2022-06-02T23%3A59%3A00.000000%2B0000&siri_route__line_refs=28774%2C28775%2C29729&siri_route__operator_refs=4%2C4%2C4&order_by=scheduled_start_time+asc

,id,siri_route_id,journey_ref,scheduled_start_time,vehicle_ref,updated_first_last_vehicle_locations,first_vehicle_location_id,last_vehicle_location_id,updated_duration_minutes,duration_minutes,journey_gtfs_ride_id,route_gtfs_ride_id,gtfs_ride_id
0,8469657,2093,2022-06-02-57859312,2022-06-02 04:00:00+00:00,79180201,2022-06-02 05:00:34.940312+00:00,445811553,445939337,2022-06-02 11:01:56.278296+00:00,22,None,9180299,9180299
1,8469656,2090,2022-06-02-57859462,2022-06-02 04:00:00+00:00,7670169,2022-06-02 05:00:34.936698+00:00,445811552,446032568,2022-06-02 11:02:08.341860+00:00,38,None,9180334,9180334
2,8473785,2090,2022-06-02-57859463,2022-06-02 04:20:00+00:00,8212185,2022-06-02 06:00:33.237922+00:00,445819131,446147667,2022-06-02 12:02:13.058656+00:00,55,None,9180323,9180323
3,8477041,2090,2022-06-02-57859464,2022-06-02 04:40:00+00:00,7609669,2022-06-02 06:00:44.954916+00:00,445951810,446300675,2022-06-02 12:02:34.024869+00:00,55,None,9180324,9180324
4,8479317,2093,2022-06-02-57859313,2022-06-02 05:00:00+00:00,7670469,2022-06-02 06:00:53.337587+00:00,446063583,446306855,2022-06-02 12:02:38.824602+00:00,39,None,9180300,9180300
5,8479023,2090,2022-06-02-57859465,2022-06-02 05:00:00+00:00,79180201,2022-06-02 06:00:52.383861+00:00,446057113,446405372,2022-06-02 12:02:38.248213+00:00,56,None,9180335,9180335
6,8482771,2090,2022-06-02-57859466,2022-06-02 05:30:00+00:00,7669969,2022-06-02 07:00:31.677957+00:00,446269232,446542313,2022-06-02 13:02:44.079571+00:00,46,None,9180336,9180336
7,8485476,2093,2022-06-02-57859314,2022-06-02 06:00:00+00:00,8212185,2022-06-02 07:00:40.449262+00:00,446428865,446660788,2022-06-02 13:02:49.859990+00:00,41,None,9180301,9180301
8,8485475,2090,2022-06-02-57859467,2022-06-02 06:00:00+00:00,7666769,2022-06-02 07:00:40.445490+00:00,446428863,446699156,2022-06-02 13:02:49.857138+00:00,48,None,9180337,9180337
9,8491389,2093,2022-06-02-57859315,2022-06-02 07:00:00+00:00,79180201,2022-06-02 08:01:56.036039+00:00,446766229,446975488,2022-06-02 14:00:24.566688+00:00,42,None,9180302,9180302
10,8491388,2090,2022-06-02-57859468,2022-06-02 07:00:00+00:00,7670469,2022-06-02 08:01:56.033131+00:00,446766227,446985396,2022-06-02 14:00:24.564943+00:00,44,None,9180338,9180338
11,8497321,2090,2022-06-02-57859469,2022-06-02 08:00:00+00:00,7667269,2022-06-02 09:00:20.080901+00:00,447074268,447263607,2022-06-02 15:00:08.246801+00:00,39,None,9180339,9180339
12,8496979,2093,2022-06-02-57859316,2022-06-02 08:00:00+00:00,7666769,2022-06-02 09:00:19.186170+00:00,447064064,447273614,2022-06-02 15:00:15.774918+00:00,43,None,9180303,9180303
13,8503188,2090,2022-06-02-57859470,2022-06-02 09:00:00+00:00,79180201,2022-06-02 10:00:11.557829+00:00,447385637,447553974,2022-06-02 16:00:09.645640+00:00,34,None,9180340,9180340
14,8502962,2093,2022-06-02-57859317,2022-06-02 09:00:00+00:00,7670469,2022-06-02 10:00:37.233463+00:00,447375593,447564377,2022-06-02 16:00:06.097590+00:00,38,None,9180304,9180304
15,8508878,2093,2022-06-02-57859318,2022-06-02 10:00:00+00:00,7667069,2022-06-02 11:01:21.861926+00:00,447680128,447929541,2022-06-02 17:00:21.729512+00:00,46,None,9180305,9180305
16,8508441,2090,2022-06-02-57859471,2022-06-02 10:00:00+00:00,7666769,2022-06-02 11:01:20.367255+00:00,447663660,447856369,2022-06-02 17:00:21.065245+00:00,35,None,9180341,9180341
17,8515501,2090,2022-06-02-57859472,2022-06-02 11:00:00+00:00,7668569,2022-06-02 12:01:09.042943+00:00,448030890,448277399,2022-06-02 18:00:23.620827+00:00,43,None,9180342,9180342
18,8514935,2093,2022-06-02-57859319,2022-06-02 11:00:00+00:00,79180201,2022-06-02 12:01:55.044790+00:00,448001861,448323620,2022-06-02 18:00:43.551953+00:00,57,None,9180306,9180306
19,8521094,2093,2022-06-02-57859320,2022-06-02 12:00:00+00:00,7668269,2022-06-02 13:02:30.695271+00:00,448341013,448704592,2022-06-02 19:01:11.884367+00:00,63,None,9180307,9180307
20,8520860,2090,2022-06-02-57859473,2022-06-02 12:00:00+00:00,7669869,2022-06-02 13:02:29.989792+00:00,448335056,448608937,2022-06-02 19:01:11.434778+00:00,46,None,9180343,9180343
21,8527291,2090,2022-06-02-57859474,2022-06-02 13:00:00+00:00,7666469,2022-06-02 14:02:47.167254+00:00,448704591,448940095,2022-06-02 20:01:27.327235+00:00,38,None,9180344,9180344
22,8526940,2093,2022-06-02-57859321,2022-06-02 13:00:00+00:00,7668569,2022-06-02 14:02:45.966734+00:00,448692320,449039771,2022-06-02 20:01:26.605383+00:00,57,None,9180308,9180308
23,8530183,2093,2022-06-02-57859322,2022-06-02 13:30:00+00:00,7669369,2022-06-02 15:02:05.839532+00:00,448883644,449196373,2022-06-02 21:01:09.441146+00:00,52,None,9180309,9180309
24,8533236,2090,2022-06-02-57859475,2022-06-02 14:00:00+00:00,7668269,2022-06-02 15:02:16.606084+00:00,449076931,449300514,2022-06-02 21:00:56.960003+00:00,38,None,9180325,9180325
25,8532701,2093,2022-06-02-57859323,2022-06-02 14:00:00+00:00,7669869,2022-06-02 15:02:14.915813+00:00,449057870,449388064,2022-06-02 21:01:16.099455+00:00,56,None,9180311,9180311
26,8536404,2090,2022-06-02-57859476,2022-06-02 14:30:00+00:00,7668569,2022-06-02 16:02:12.265313+00:00,449270662,449484531,2022-06-02 22:01:13.768061+00:00,38,None,9180326,9180326
27,8535832,2093,2022-06-02-57859324,2022-06-02 14:30:00+00:00,7666469,2022-06-02 16:02:10.521267+00:00,449239503,449478878,2022-06-02 22:01:12.431639+00:00,42,None,9180312,9180312
28,8539442,2090,2022-06-02-57859477,2022-06-02 15:00:00+00:00,79180201,2022-06-02 16:01:52.468978+00:00,449450350,449650018,2022-06-02 22:01:17.242894+00:00,36,None,9180327,9180327
29,8538691,2093,2022-06-02-57859325,2022-06-02 15:00:00+00:00,7666869,2022-06-02 16:02:28.727427+00:00,449415709,449644711,2022-06-02 22:01:21.147334+00:00,42,None,9180313,9180313
30,8541388,2090,2022-06-02-57859478,2022-06-02 15:30:00+00:00,7669869,2022-06-02 17:02:47.918686+00:00,449579307,449769093,2022-06-02 22:01:36.746083+00:00,36,None,9180328,9180328
31,8544244,2093,2022-06-02-57859327,2022-06-02 16:00:00+00:00,7667769,2022-06-02 17:02:56.041852+00:00,449737872,449991474,2022-06-02 23:01:31.436310+00:00,54,None,9180315,9180315
32,8546820,2093,2022-06-02-57859328,2022-06-02 16:30:00+00:00,7668569,2022-06-02 18:02:33.312354+00:00,449886360,450105554,2022-06-03 00:02:13.611124+00:00,51,None,9180316,9180316
33,8546819,2090,2022-06-02-57859479,2022-06-02 16:30:00+00:00,7666869,2022-06-02 18:02:33.309229+00:00,449886358,450055660,2022-06-03 00:02:13.609252+00:00,39,None,9180329,9180329
34,8549231,2093,2022-06-02-57859329,2022-06-02 17:00:00+00:00,8212185,2022-06-02 18:02:42.841045+00:00,450020643,450200988,2022-06-03 00:02:21.671183+00:00,45,None,9180317,9180317
35,8551789,2090,2022-06-02-57859480,2022-06-02 17:30:00+00:00,7667769,2022-06-02 19:00:12.571403+00:00,450162075,450271423,2022-06-03 00:02:26.566276+00:00,29,None,9180330,9180330
36,8553484,2093,2022-06-02-57859330,2022-06-02 18:00:00+00:00,7668669,2022-06-02 19:00:16.876723+00:00,450256322,450403776,2022-06-03 01:00:16.748852+00:00,44,None,9180318,9180318
37,8555593,2090,2022-06-02-57859481,2022-06-02 18:30:00+00:00,8212185,2022-06-02 20:00:35.827882+00:00,450378225,450469313,2022-06-03 02:00:11.758045+00:00,32,None,9180331,9180331
38,8558577,5660,2022-06-02-58928054,2022-06-02 19:30:00+00:00,7668669,2022-06-02 21:00:46.080504+00:00,450533621,450615185,2022-06-03 02:00:18.983307+00:00,35,None,9185827,9185827
39,8560347,2093,2022-06-02-57859332,2022-06-02 20:00:00+00:00,7670369,2022-06-02 21:00:28.426337+00:00,450616974,450705318,2022-06-03 03:00:05.196279+00:00,46,None,9180320,9180320
40,8561042,5660,2022-06-02-58498711,2022-06-02 20:30:00+00:00,7668769,2022-06-02 21:00:30.783744+00:00,450667702,450723750,2022-06-03 03:00:11.560067+00:00,33,None,9185826,9185826
41,8561938,2093,2022-06-03-57859333,2022-06-02 21:00:00+00:00,8212185,2022-06-02 22:00:53.724356+00:00,450720465,450763309,2022-06-03 04:00:21.335056+00:00,35,None,9242828,9242828

## Choose a ride

There are usually a lot of rides for a given route, the following code gets the first ride which occured at or after 7:00 in the morning

(the rides are already ordered in ascending order based on dates, so first one which is after or on 7 will be the right one)

In [6]:
for siri_ride in siri_rides:
    if siri_ride['scheduled_start_time'].hour >= 7:
        break
siri_ride

{'id': 8491389,
 'siri_route_id': 2093,
 'journey_ref': '2022-06-02-57859315',
 'scheduled_start_time': datetime.datetime(2022, 6, 2, 7, 0, tzinfo=datetime.timezone.utc),
 'vehicle_ref': '79180201',
 'updated_first_last_vehicle_locations': datetime.datetime(2022, 6, 2, 8, 1, 56, 36039, tzinfo=datetime.timezone.utc),
 'first_vehicle_location_id': 446766229,
 'last_vehicle_location_id': 446975488,
 'updated_duration_minutes': datetime.datetime(2022, 6, 2, 14, 0, 24, 566688, tzinfo=datetime.timezone.utc),
 'duration_minutes': 42,
 'journey_gtfs_ride_id': None,
 'route_gtfs_ride_id': 9180302,
 'gtfs_ride_id': 9180302}

## Get the ride-stops for this ride

Siri ride-stops contain all the list of stops on this ride, the vehicle locations are then related to the ride stops

this contains data from related tables:

* `gtfs_stop__city` / `gtfs_stop__name`: the stop city/name from the gtfs data
* `gtfs_ride_stop__departure_time`: the planned departure time based on the gtfs data
* `nearest_siri_vehicle_location__recorded_at_time`: the date/time from SIRI data of the relevant bus which was on this route/ride and nearest to this gtfs stop (based on lat/lon)

In [7]:
siri_ride_stops = stride.get('/siri_ride_stops/list', {
    'siri_ride_ids': str(siri_ride['id']),
    'order_by': 'order asc',
    'expand_related_data': True
}, pre_requests_callback='print')
df = pd.DataFrame(siri_ride_stops)
df.loc[:, [
    'order', 'gtfs_stop__city', 'gtfs_stop__name', 'gtfs_ride_stop__departure_time', 
    'nearest_siri_vehicle_location__recorded_at_time'
]]

https://open-bus-stride-api.hasadna.org.il/siri_ride_stops/list?siri_ride_ids=8491389&order_by=order+asc&expand_related_data=True

,order,gtfs_stop__city,gtfs_stop__name,gtfs_ride_stop__departure_time,nearest_siri_vehicle_location__recorded_at_time
0,1,ירושלים,היכל המשפט/אבא אבן,None,None
1,2,ירושלים,בנייני האומה,None,None
2,3,ירושלים,גשר המיתרים/שד' הרצל,None,None
3,4,ירושלים,אצטדיון טדי/א''ס ביתר,None,None
4,5,גוש עציון,מחסום המנהרות,None,None
5,6,אפרת,אפרת שער צפוני/כניסה,None,None
6,7,אפרת,דוד המלך/הדבש,None,None
7,9,אפרת,שדרות רחל אמנו/שדרות דוד המלך,None,None
8,10,אפרת,הדקל/עזרא,None,None
9,11,אפרת,שדרות דוד המלך/השיירות,None,None
10,12,אפרת,שדרות דוד המלך/הגפן,None,None